version: '3.9'

services:
  db:
    image: postgres:16
    container_name: rustemr-db
    restart: always
    environment:
      POSTGRES_DB: rustemr_dev
      POSTGRES_USER: rustemr
      POSTGRES_PASSWORD: rustemr
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rustemr-backend
    container_name: rustemr-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rustemr:rustemr@db:5432/rustemr_dev
      RUST_LOG: debug
      SECRET: supersecretkey
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rustemr-frontend
    container_name: rustemr-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  db_data:
