version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rustemr
      POSTGRES_PASSWORD: rustemr
      POSTGRES_DB: rustemr_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rustemr:rustemr@db:5432/rustemr_dev
      RUST_LOG: debug
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
volumes:
  db_data:
