# Jekyll configuration for GitHub Pages

title: "RustEMR Documentation"
description: "Comprehensive guides and references for RustEMR."
baseurl: "/rustemr"  # project page base
url: "https://UbudCare.github.io/rustemr"
theme: minima

# Exclude files/directories
exclude:
  - "README.md"
